export const ItemData = [
    {
        id : "1",
        secondid:"1a",
        image:"./avlProductIMG/laptop1.jpg",
        name:"Lenovo IdeaPad Slim 5 15ITL05",
        price:1000,
        description:"Sở hữu thiết kế mỏng nhẹ và thanh lịch, Lenovo IdeaPad Slim 5 15ITL05 i5 1135G7 (82FG001PVN) không chỉ là một mẫu laptop thời trang, mà còn mang trên mình sức mạnh vô cùng mạnh mẽ đến từ bộ vi xử lý Intel Core i5 thế hệ thứ 11 giúp bạn hoàn thành xuất sắc mọi công việc.",
        avialable:"available",
        categories:"Lenovo",
        cpu : "Intel Core i5 Tiger Lake 1135G72.40 GHz",
        ram : "8 GBDDR4 (On board)3200 MHz",
        harddrive : "SSD 512 GB NVMe PCIe",
        moniter : "Card tích hợpIntel Iris Xe Graphics",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "2",
        secondid:"2a",
        image:"./avlProductIMG/laptop2.jpg",
        name:"Lenovo IdeaPad 3 15ITL6 i5",
        price:1500,
        description:"Laptop Lenovo IdeaPad 3 15ITL6 i5 (82H800042VN) với thiết kế mỏng nhẹ đẹp mắt cùng hiệu năng ổn định giúp bạn hoàn thành công việc một cách nhanh chóng, hiệu quả.Thiết kế gọn nhẹ, phong cách trẻ trung",
        avialable:"available",
        categories:"Lenovo",
        cpu : "Intel Core i5 Tiger Lake 1135G72.40 GHz",
        ram : "8 GBDDR4 (On board 4GB +1 khe 4GB)3200 MHz",
        harddrive : "SSD 512 GB NVMe PCIeHỗ trợ khe cắm HDD SATA",
        moniter : "Card tích hợpIntel Iris Xe Graphics",
        operatingsystem :"Windows 10 Home SL",
        realese : "2021",
    },
    {
        id : "3",
        secondid:"3a",
        image:"./avlProductIMG/laptop3.jpg",
        name:"Acer Aspire 7 Gaming A715 41G",
        price:2000,
        description:"Acer Aspire 7 A715 41G R150 R7 (NH.Q8SSV.004) được thiết kế gọn gàng với cấu hình mạnh mẽ nhờ CPU AMD Ryzen 7 và card đồ hoạ NVIDIA GeForce GTX 1650Ti giúp tối ưu trải nghiệm chơi game, đáp ứng đa dạng nhu cầu sử dụng.Hiệu năng mạnh mẽ với chip AMD Ryzen 7",
        avialable:"available",
        categories:"Acer",
        cpu : "AMD Ryzen 7 3750H2.30 GHz",
        ram : "8 GBDDR4 (2 khe)2400 MHz",
        harddrive : "SSD 512 GB NVMe PCIe",
        moniter : "SSD 512 GB NVMe PCIe",
        operatingsystem :"15.6 Full HD",
        realese : "available",
    },
    {
        id : "4",
        secondid:"4a",
        image:"./avlProductIMG/laptop4.jpg",
        name:"HP Pavilion 15 eg0505TU i5",
        price:500,
        description:"Hiệu năng làm việc và học tập mạnh mẽ đến từ HP Pavilion 15 eg0505TU i5 1135G7 (46M02PA) cùng kiểu dáng thanh lịch là bạn đồng hành lý tưởng, đáp ứng mọi nhu cầu hàng ngày của người dùng.Thiết kế tinh tế và đẳng cấp với tông màu vàng đồng thời thượng",
        avialable:"available",
        categories:"HP",
        cpu : "Intel Core i5 Tiger Lake 1135G72.40 GHz",
        ram : "8 GBDDR4 2 khe (1 khe 4GB + 1 khe 4GB)3200 MHz",
        harddrive : "SSD 512 GB NVMe PCIe",
        moniter : "15.6 Full HD (1920 x 1080)",
        operatingsystem :"Windows 10 Home SL",
        realese : "2021",
    },
    {
        id : "5",
        secondid:"5a",
        image:"./avlProductIMG/laptop5.jpg",
        name:"Dell Gaming G3 15 i7 10750H",
        price:600,
        description:"Laptop Dell G3 15 i7 (P89F002BWH) thuộc dòng laptop gaming với cấu hình mạnh mẽ, thiết kế trang nhã và rất sang trọng, dễ lựa chọn cho cả người đi đọc, đi làm, là 1 phiên bản tốt để lựa chọn cho cả nhu cầu làm việc, học tập và chơi game giải trí.Sang trọng, tinh tế, phong cách trẻ trung, hiện đại",
        avialable:"available",
        categories:"Dell",
        cpu : "Intel Core i7 Comet Lake 10750H2.60 GHz",
        ram : "16 GBDDR4 2 khe (1 khe 8GB + 1 khe 8GB)2933 MHz",
        harddrive : "SSD 512 GB NVMe PCIeHỗ trợ thêm 1 khe cắm SSD M.2 PCIe mở rộng",
        moniter : "15.6 Full HD (1920 x 1080), 120Hz",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "6",
        secondid:"6a",
        image:"./avlProductIMG/laptop6.jpg",
        name:"Asus TUF Gaming FX506LH i5",
        price:1200,
        description:"Với sự mạnh mẽ, bền bỉ từ thiết kế vẻ ngoài lẫn bên trong cấu hình, Asus TUF Gaming FX506LH (HN002T) sẽ là một trợ thủ đắc lực của bạn trong trò chơi yêu thích và cả những tác vụ nặng khác. Đa nhiệm mượt mà với Chip Intel Core i5 thế hệ 10 tiêu chuẩn gaming",
        avialable:"available",
        categories:"Asus",
        cpu : "Intel Core i5 Comet Lake 10300H2.50 GHz",
        ram : "8 GBDDR4 (2 khe)2933 MHz",
        harddrive : "SSD 512 GB NVMe PCIeHỗ trợ thêm 1 khe cắm SSD M.2 PCIe mở rộng",
        moniter : "15.6 Full HD (1920 x 1080), 144Hz",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "7",
        secondid:"7a",
        image:"./avlProductIMG/laptop7.jpg",
        name:"Lenovo Ideapad 5 15ITL05 i5",
        price:800,
        description:"Laptop Lenovo Ideapad 5 15ITL05 i5 1135G7 (82FG00P5VN) là một sản phẩm hoàn hảo từ thiết kế thiết kế thông minh, tinh tế đến cấu hình mạnh mẽ của Intel thế hệ 11, đáp ứng mọi nhu cầu cho bạn từ tác vụ văn phòng đến đồ họa chuyên nghiệp, giải trí, chơi game đơn giản, rất xứng đáng để bạn sở hữu ngay.",
        avialable:"available",
        categories:"Lenovo",
        cpu : "Intel Core i5 Tiger Lake 1135G72.40 GHz",
        ram : "8 GBDDR4 (On board)3200 MHz",
        harddrive : "Hỗ trợ khe cắm HDD SATASSD 512 GB NVMe PCIe",
        moniter : "15.6 Full HD (1920 x 1080)",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "8",
        secondid:"8a",
        image:"./avlProductIMG/laptop8.jpg",
        name:"MacBook Pro M1 2020 Space",
        price:1300,
        description:"Apple Macbook Pro M1 2020 (MYD82SA/A) sở hữu thiết kế sang trọng từ kim loại nguyên khối được kế thừa từ các thế hệ trước nhưng bên trong là một cấu hình cực kỳ đáng gờm. Với chip M1 lần đầu tiên xuất hiện trên MacBook Pro, hiệu năng CPU của máy tăng đến 2.8 lần, hiệu năng GPU tăng 5 lần.Thiết kế nguyên khối từ kim loại tái chế",
        avialable:"available",
        categories:"APPLE",
        cpu : "Apple M1",
        ram : "8 GB",
        harddrive : "SSD 256 GB",
        moniter : "13.3 Retina (2560 x 1600)",
        operatingsystem :"Mac OS",
        realese : "2020",
    },
    {
        id : "9",
        secondid:"9a",
        image:"./avlProductIMG/laptop9.jpg",
        name:"Acer Aspire A315 56 308N i3",
        price:2000,
        description:"Laptop Acer Aspire A315 56 308N i3 (NX.HS5SV.00C) là mẫu laptop học tập văn phòng thuộc phân khúc giá thấp. Máy trang bị vi xử lý thế hệ mới của Intel, cho hiệu năng đủ dùng đối với các nhu cầu cơ bản, phù hợp với học sinh và sinh viên.Chip xử lý tân tiến nhất",
        avialable:"available",
        categories:"Acer",
        cpu : "Intel Core i3 Ice Lake 1005G11.20 GHz",
        ram : "4 GBDDR4 (On board +1 khe)2400 MHz",
        harddrive : "SSD 256 GB NVMe PCIeHỗ trợ khe cắm HDD SATA",
        moniter : "15.6 Full HD (1920 x 1080)",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "10",
        secondid:"10a",
        image:"./avlProductIMG/laptop10.jpg",
        name:"Lenovo Ideapad Gaming 3",
        price:700,
        description:"Laptop Lenovo Ideapad Gaming 3 15IMH05 i7 (81Y4013UVN) là dòng laptop gaming tầm trung với thiết kế tối giản, vẻ ngoài không quá hầm hố nhưng vẫn sở hữu hiệu năng cao đáp ứng tốt từ nhu cầu làm việc đến giải trí.Thiết kế hiện đại, tối giản",
        avialable:"available",
        categories:"Lenovo",
        cpu : "Intel Core i7 Comet Lake 10750H2.60 GHz",
        ram : "8 GBDDR4 (2 khe)2933 MHz",
        harddrive : "Hỗ trợ khe cắm HDD SATASSD 512 GB NVMe PCIe",
        moniter : "15.6 Full HD (1920 x 1080), 120Hz",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "11",
        secondid:"11a",
        image:"./avlProductIMG/laptop9.jpg",
        name:"Acer Swift 3 SF314 511 56G1 i5",
        price:2400,
        description:"Laptop Acer Swift 3 SF314 511 56G1 i5 (NX.HS5SV.00C) là mẫu laptop học tập văn phòng thuộc phân khúc giá thấp. Máy trang bị vi xử lý thế hệ mới của Intel, cho hiệu năng đủ dùng đối với các nhu cầu cơ bản, phù hợp với học sinh và sinh viên.Chip xử lý tân tiến nhất",
        avialable:"available",
        categories:"Acer ",
        cpu : "Intel Core i3 Ice Lake 1005G11.20 GHz",
        ram : "4 GBDDR4 (On board +1 khe)2400 MHz",
        harddrive : "SSD 256 GB NVMe PCIeHỗ trợ khe cắm HDD SATA",
        moniter : "15.6 Full HD (1920 x 1080)",
        operatingsystem :"Windows 10 Home SL",
        realese : "2020",
    },
    {
        id : "12",
        secondid:"12a",
        image:"./avlProductIMG/laptop4.jpg",
        name:"HP 15s fq2559TU i5 1135G7 (46M27PA)",
        price:500,
        description:"Hiệu năng làm việc và học tập mạnh mẽ đến từ HP Pavilion 15 eg0505TU i5 1135G7 (46M02PA) cùng kiểu dáng thanh lịch là bạn đồng hành lý tưởng, đáp ứng mọi nhu cầu hàng ngày của người dùng.Thiết kế tinh tế và đẳng cấp với tông màu vàng đồng thời thượng",
        avialable:"available",
        categories:"HP",
        cpu : "Intel Core i5 Tiger Lake 1135G72.40 GHz",
        ram : "8 GBDDR4 2 khe (1 khe 4GB + 1 khe 4GB)3200 MHz",
        harddrive : "SSD 512 GB NVMe PCIe",
        moniter : "15.6 Full HD (1920 x 1080)",
        operatingsystem :"Windows 10 Home SL",
        realese : "2021",
    },
];